### ISSUE TITLE
Design restaking: Staking rewards exit the contract (no compouding)

### ISSUE THREAD

**Issue by 0x-r4bbit** [logos-co/staking#17]
Status Staking Summary describes the vaults and the re-staking process as follows:

> Additionally, vaults can only be opened once by an initial stake, after that new stakes can not manually be added to the vault, they must be made as new vaults. Vaults can only grow from re-staking/compounding rewards earned by that vault. Earned SNT staking rewards can only be re-staked into the respective vault that earned them (note rewards can be withdrawn to a user’s address from any vault based on Withdraw logic discussed above).

The current implementation does not follow this logic as additional stake can be added after initial stake, re-staking is not possible without withdrawal. See the original document for context. These processes should reflect the cooldown periods that are a separate issue.

**Comment by 0x-r4bbit** [comment]
@mart1n-xyz I remember I had a discussion with @3esmit about restaking and whether users should be able to add stakes to existing vaults or if adding stakes should **always** result in a new vault.

Can you leave your thoughts on this here so we can settle this with the correct implementation?

**Comment by mart1n-xyz** [comment]
I think our discussion ended at the point where we agreed that having users add stake is not worth the additional complexity. However, this has to be compensated by specific vault structure for restaking.

Specifically, one of the ideas was to have a special vault (in fact an AA wallet, covered in https://github.com/logos-co/staking/issues/34) where all rewards (from user's all vaults) are collected. Then if the user decides to restake, a new vault is deployed from there. Or if there is a withdrawal request, the cooldown applies and the withdrawal is processed. 

The problem is that this does lead to a vault explosion over time. Hence there was a follow-up and inconclusive discussion whether we could enable vaults without lock to be merged to mitigate the number of vault instances. This is, nevertheless, the same as allowing adding stake.

**Comment by 0x-r4bbit** [comment]
With the latest work done on MP estimation (#97) we no longer allow for adding stake to existing vaults.
For new stake actions, new vaults will be created.
